/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './lib/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: {
          default: 'var(--background-default)',
          surface: 'var(--background-surface)',
          elevated: 'var(--background-elevated)',
          header: 'var(--background-header)',
          sidebar: 'var(--background-sidebar)',
          sidebarSubtle: 'var(--background-sidebar-subtle)',
          accent: 'var(--background-accent)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          inverse: 'var(--text-inverse)',
          inverseMuted: 'var(--text-inverse-muted)',
        },
        border: {
          default: 'var(--border-default)',
          light: 'var(--border-light)',
          focus: 'var(--border-focus)',
        },
        accent: {
          primary: 'var(--accent-primary)',
          onPrimary: 'var(--accent-on-primary)',
          secondary: 'var(--accent-secondary)',
          success: 'var(--accent-success)',
          warning: 'var(--accent-warning)',
          danger: 'var(--accent-danger)',
        },
      },
      spacing: {
        0: 'var(--space-0)',
        px: 'var(--space-2)',
        0.5: 'var(--space-2)',
        1: 'var(--space-4)',
        2: 'var(--space-8)',
        3: 'var(--space-12)',
        4: 'var(--space-16)',
        6: 'var(--space-24)',
        8: 'var(--space-32)',
        10: 'var(--space-40)',
        12: 'var(--space-48)',
        16: 'var(--space-64)',
        20: 'var(--space-80)',
        24: 'var(--space-96)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-lg)',
        '3xl': 'var(--radius-xl)',
        full: 'var(--radius-pill)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      fontFamily: {
        sans: 'var(--font-body)',
      },
      transitionDuration: {
        fast: 'var(--motion-fast)',
        normal: 'var(--motion-normal)',
        slow: 'var(--motion-slow)',
      },
      transitionTimingFunction: {
        standard: 'var(--motion-standard)',
      },
      zIndex: {
        header: 'var(--z-header)',
        sidebar: 'var(--z-sidebar)',
        drawer: 'var(--z-drawer)',
        modal: 'var(--z-modal)',
        ai: 'var(--z-ai-panel)',
      },
    },
  },
  plugins: [],
};
