import type { WorkflowContract } from './types';

export const workflowRegistry: WorkflowContract[] = [
  {
    id: 'employee-creation-approval',
    module: 'HRMS',
    type: 'sequential',
    configurable: true,
    supportsDelegation: true,
    supportsEscalation: true,
    supportsNotifications: true,
    supportsAuditTrail: true,
    supportsAnalytics: true,
    supportsAiAssistance: true,
  },
  {
    id: 'loan-credit-committee',
    module: 'Lending',
    type: 'parallel',
    configurable: true,
    supportsDelegation: true,
    supportsEscalation: true,
    supportsNotifications: true,
    supportsAuditTrail: true,
    supportsAnalytics: true,
    supportsAiAssistance: true,
  },
  {
    id: 'journal-approval',
    module: 'Accounting',
    type: 'conditional',
    configurable: true,
    supportsDelegation: true,
    supportsEscalation: true,
    supportsNotifications: true,
    supportsAuditTrail: true,
    supportsAnalytics: true,
    supportsAiAssistance: true,
  },
  {
    id: 'treasury-transfer',
    module: 'Treasury',
    type: 'dynamic',
    configurable: true,
    supportsDelegation: true,
    supportsEscalation: true,
    supportsNotifications: true,
    supportsAuditTrail: true,
    supportsAnalytics: true,
    supportsAiAssistance: true,
  },
];
