export const componentRegistry = [
  { layer: 'foundation', name: 'Button', contract: 'semantic variants, loading-ready, keyboard focus' },
  { layer: 'foundation', name: 'IconButton', contract: 'accessible label, icon-only command surface' },
  { layer: 'foundation', name: 'Badge', contract: 'semantic tones mapped to theme tokens' },
  { layer: 'foundation', name: 'Avatar', contract: 'tenant-safe initials or icon identity' },
  { layer: 'foundation', name: 'Chip', contract: 'filter chip with selected state' },
  { layer: 'foundation', name: 'Typography', contract: 'shared type scale and semantic tones' },
  { layer: 'layout', name: 'PageContainer', contract: 'responsive page width and gutters' },
  { layer: 'layout', name: 'WorkspaceHeader', contract: 'title, description, and action hierarchy' },
  { layer: 'layout', name: 'Drawer', contract: 'right-side context without losing list state' },
  { layer: 'navigation', name: 'Breadcrumb', contract: 'maximum-depth trail with screen-reader label' },
  { layer: 'navigation', name: 'SearchBar', contract: 'global/local search input anatomy' },
  { layer: 'navigation', name: 'Tabs', contract: 'keyboard-visible tab state and panels' },
  { layer: 'forms', name: 'TextInput', contract: 'label, helper, error, required, focus ring' },
  { layer: 'forms', name: 'Textarea', contract: 'long text capture with validation surface' },
  { layer: 'forms', name: 'Checkbox', contract: 'binary input with label association' },
  { layer: 'forms', name: 'Toggle', contract: 'switch role with selected state' },
  { layer: 'data-display', name: 'MetricCard', contract: 'KPI display with semantic tone' },
  { layer: 'data-display', name: 'EnterpriseTable', contract: 'typed columns, empty state, responsive overflow' },
  { layer: 'workflow', name: 'ApprovalCard', contract: 'approval status, amount, and action' },
  { layer: 'workflow', name: 'Timeline', contract: 'ordered activity and audit events' },
  { layer: 'feedback', name: 'Alert', contract: 'semantic feedback message' },
  { layer: 'feedback', name: 'EmptyState', contract: 'recoverable empty workspace' },
  { layer: 'feedback', name: 'LoadingState', contract: 'skeleton-first loading surface' },
  { layer: 'ai', name: 'AISummary', contract: 'FinDNA summary plus suggested actions' },
  { layer: 'banking', name: 'Customer360Card', contract: 'customer risk and relationship value summary' },
  { layer: 'banking', name: 'LoanSummaryCard', contract: 'loan exposure and status summary' },
  { layer: 'security', name: 'PermissionGuard', contract: 'role/permission gated rendering' },
  { layer: 'security', name: 'RoleBadge', contract: 'visible role and elevated access indicator' },
  { layer: 'dashboard', name: 'DashboardLayout', contract: 'role-based dashboard composition shell' },
  { layer: 'dashboard', name: 'DashboardGrid', contract: 'responsive 12-column widget grid' },
  { layer: 'dashboard', name: 'WidgetContainer', contract: 'shared widget chrome, metadata, refresh policy' },
  { layer: 'dashboard', name: 'KPIWidget', contract: 'status-first KPI with trend and drill-down target' },
  { layer: 'dashboard', name: 'ChartWidget', contract: 'summary chart with drill-down support' },
  { layer: 'dashboard', name: 'AlertWidget', contract: 'actionable alerts only' },
  { layer: 'dashboard', name: 'TaskWidget', contract: 'task center grouped by urgency and owner' },
  { layer: 'dashboard', name: 'ApprovalWidget', contract: 'pending decisions with SLA context' },
  { layer: 'dashboard', name: 'ActivityWidget', contract: 'recent activity and audit event stream' },
  { layer: 'dashboard', name: 'AISummaryWidget', contract: 'explain-why AI insight surface' },
] as const;

export type ComponentRegistryItem = (typeof componentRegistry)[number];
