"""add vehicle and property loan tables

Revision ID: 005
Revises: 004
Create Date: 2026-01-07

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade():
    """Add vehicle and property loan extension tables"""
    
    # ============================================
    # VEHICLE LOAN TABLES
    # ============================================
    
    # Vehicle Dealers Table
    op.create_table(
        'vehicle_dealers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(50), nullable=False),
        sa.Column('dealer_code', sa.String(50), nullable=False),
        sa.Column('dealer_name', sa.String(200), nullable=False),
        sa.Column('brand', sa.String(100)),
        sa.Column('contact_person', sa.String(100)),
        sa.Column('mobile', sa.String(20), nullable=False),
        sa.Column('email', sa.String(100)),
        sa.Column('phone', sa.String(20)),
        sa.Column('address_line1', sa.String(200)),
        sa.Column('address_line2', sa.String(200)),
        sa.Column('city', sa.String(100)),
        sa.Column('state', sa.String(50)),
        sa.Column('pincode', sa.String(10)),
        sa.Column('gstin', sa.String(15)),
        sa.Column('pan', sa.String(10)),
        sa.Column('business_type', sa.String(50)),
        sa.Column('agreement_start_date', sa.Date()),
        sa.Column('agreement_end_date', sa.Date()),
        sa.Column('commission_percentage', sa.Numeric(5, 2)),
        sa.Column('payout_terms', sa.String(100)),
        sa.Column('bank_name', sa.String(100)),
        sa.Column('bank_account_number', sa.String(50)),
        sa.Column('bank_ifsc', sa.String(11)),
        sa.Column('bank_branch', sa.String(100)),
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.Column('is_verified', sa.Boolean(), default=False),
        sa.Column('additional_info', postgresql.JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('created_by', postgresql.UUID(as_uuid=True)),
        sa.Column('updated_by', postgresql.UUID(as_uuid=True)),
        sa.Column('is_deleted', sa.Boolean(), default=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.UniqueConstraint('dealer_code')
    )
    op.create_index('idx_dealer_tenant_code', 'vehicle_dealers', ['tenant_id', 'dealer_code'])
    op.create_index('idx_dealer_active', 'vehicle_dealers', ['tenant_id', 'is_active'])
    
    # Vehicle Loan Details Table
    op.create_table(
        'vehicle_loan_details',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(50), nullable=False),
        sa.Column('loan_application_id', sa.Integer(), nullable=False),
        sa.Column('vehicle_type', sa.String(50), nullable=False),
        sa.Column('vehicle_condition', sa.String(50), nullable=False),
        sa.Column('manufacturer', sa.String(100), nullable=False),
        sa.Column('model', sa.String(100), nullable=False),
        sa.Column('variant', sa.String(100)),
        sa.Column('manufacturing_year', sa.Integer()),
        sa.Column('color', sa.String(50)),
        sa.Column('fuel_type', sa.String(50)),
        sa.Column('chassis_number', sa.String(50)),
        sa.Column('engine_number', sa.String(50)),
        sa.Column('registration_number', sa.String(20)),
        sa.Column('registration_date', sa.Date()),
        sa.Column('registration_state', sa.String(50)),
        sa.Column('registration_rto', sa.String(100)),
        sa.Column('ex_showroom_price', sa.Numeric(15, 2), nullable=False),
        sa.Column('on_road_price', sa.Numeric(15, 2), nullable=False),
        sa.Column('down_payment', sa.Numeric(15, 2), nullable=False),
        sa.Column('financed_amount', sa.Numeric(15, 2), nullable=False),
        sa.Column('loan_to_value', sa.Numeric(5, 2)),
        sa.Column('dealer_id', sa.Integer()),
        sa.Column('dealer_name', sa.String(200)),
        sa.Column('dealer_contact', sa.String(20)),
        sa.Column('dealer_location', sa.String(200)),
        sa.Column('dealer_invoice_number', sa.String(50)),
        sa.Column('dealer_invoice_date', sa.Date()),
        sa.Column('is_registered', sa.Boolean(), default=False),
        sa.Column('hypothecation_status', sa.String(50), default='pending'),
        sa.Column('current_owner', sa.String(200)),
        sa.Column('seating_capacity', sa.Integer()),
        sa.Column('gross_vehicle_weight', sa.Numeric(10, 2)),
        sa.Column('vehicle_class', sa.String(50)),
        sa.Column('body_type', sa.String(50)),
        sa.Column('rc_book_number', sa.String(50)),
        sa.Column('rc_book_uploaded', sa.Boolean(), default=False),
        sa.Column('invoice_uploaded', sa.Boolean(), default=False),
        sa.Column('insurance_uploaded', sa.Boolean(), default=False),
        sa.Column('additional_info', postgresql.JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('created_by', postgresql.UUID(as_uuid=True)),
        sa.Column('updated_by', postgresql.UUID(as_uuid=True)),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id']),
        sa.ForeignKeyConstraint(['dealer_id'], ['vehicle_dealers.id']),
        sa.UniqueConstraint('loan_application_id'),
        sa.UniqueConstraint('chassis_number'),
        sa.UniqueConstraint('engine_number'),
        sa.UniqueConstraint('registration_number')
    )
    op.create_index('idx_vehicle_tenant_loan', 'vehicle_loan_details', ['tenant_id', 'loan_application_id'])
    op.create_index('idx_vehicle_chassis_engine', 'vehicle_loan_details', ['chassis_number', 'engine_number'])
    op.create_index('idx_vehicle_registration', 'vehicle_loan_details', ['registration_number'])
    
    # Vehicle RTO Tracking Table
    op.create_table(
        'vehicle_rto_tracking',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(50), nullable=False),
        sa.Column('vehicle_loan_id', sa.Integer(), nullable=False),
        sa.Column('loan_application_id', sa.Integer(), nullable=False),
        sa.Column('rto_state', sa.String(50), nullable=False),
        sa.Column('rto_office', sa.String(100), nullable=False),
        sa.Column('rto_code', sa.String(20)),
        sa.Column('hypothecation_status', sa.String(50), default='pending'),
        sa.Column('lender_name', sa.String(200)),
        sa.Column('form35_submitted', sa.Boolean(), default=False),
        sa.Column('form35_submission_date', sa.Date()),
        sa.Column('form35_reference_number', sa.String(50)),
        sa.Column('form35_fees_paid', sa.Numeric(10, 2)),
        sa.Column('hypothecation_marked_date', sa.Date()),
        sa.Column('hypothecation_endorsement_number', sa.String(50)),
        sa.Column('rc_book_updated', sa.Boolean(), default=False),
        sa.Column('physical_rc_received', sa.Boolean(), default=False),
        sa.Column('loan_closed_date', sa.Date()),
        sa.Column('noc_generated_date', sa.Date()),
        sa.Column('noc_sent_to_customer', sa.Boolean(), default=False),
        sa.Column('noc_reference_number', sa.String(50)),
        sa.Column('form35_removal_submitted', sa.Boolean(), default=False),
        sa.Column('form35_removal_date', sa.Date()),
        sa.Column('form35_removal_reference', sa.String(50)),
        sa.Column('hypothecation_removed_date', sa.Date()),
        sa.Column('updated_rc_issued', sa.Boolean(), default=False),
        sa.Column('last_followup_date', sa.Date()),
        sa.Column('next_followup_date', sa.Date()),
        sa.Column('followup_comments', sa.Text()),
        sa.Column('issues_encountered', sa.Text()),
        sa.Column('resolution_notes', sa.Text()),
        sa.Column('form35_document_path', sa.String(500)),
        sa.Column('noc_document_path', sa.String(500)),
        sa.Column('rc_copy_path', sa.String(500)),
        sa.Column('additional_info', postgresql.JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('created_by', postgresql.UUID(as_uuid=True)),
        sa.Column('updated_by', postgresql.UUID(as_uuid=True)),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['vehicle_loan_id'], ['vehicle_loan_details.id']),
        sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id']),
        sa.UniqueConstraint('vehicle_loan_id')
    )
    op.create_index('idx_rto_tenant_status', 'vehicle_rto_tracking', ['tenant_id', 'hypothecation_status'])
    op.create_index('idx_rto_followup', 'vehicle_rto_tracking', ['tenant_id', 'next_followup_date'])
    
    # Vehicle Insurance Table
    op.create_table(
        'vehicle_insurance',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(50), nullable=False),
        sa.Column('vehicle_loan_id', sa.Integer(), nullable=False),
        sa.Column('loan_application_id', sa.Integer(), nullable=False),
        sa.Column('customer_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('policy_number', sa.String(50), nullable=False),
        sa.Column('policy_type', sa.String(50), nullable=False),
        sa.Column('insurance_company', sa.String(200), nullable=False),
        sa.Column('insurance_provider_code', sa.String(50)),
        sa.Column('idv_amount', sa.Numeric(15, 2), nullable=False),
        sa.Column('coverage_amount', sa.Numeric(15, 2)),
        sa.Column('is_zero_depreciation', sa.Boolean(), default=False),
        sa.Column('is_engine_protection', sa.Boolean(), default=False),
        sa.Column('is_return_to_invoice', sa.Boolean(), default=False),
        sa.Column('premium_amount', sa.Numeric(15, 2), nullable=False),
        sa.Column('own_damage_premium', sa.Numeric(15, 2)),
        sa.Column('third_party_premium', sa.Numeric(15, 2)),
        sa.Column('gst_amount', sa.Numeric(15, 2)),
        sa.Column('total_premium', sa.Numeric(15, 2), nullable=False),
        sa.Column('policy_start_date', sa.Date(), nullable=False),
        sa.Column('policy_end_date', sa.Date(), nullable=False),
        sa.Column('policy_issued_date', sa.Date()),
        sa.Column('premium_paid', sa.Boolean(), default=False),
        sa.Column('premium_paid_date', sa.Date()),
        sa.Column('premium_payment_mode', sa.String(50)),
        sa.Column('premium_receipt_number', sa.String(50)),
        sa.Column('is_renewal', sa.Boolean(), default=False),
        sa.Column('previous_policy_number', sa.String(50)),
        sa.Column('renewal_notice_sent', sa.Boolean(), default=False),
        sa.Column('renewal_notice_date', sa.Date()),
        sa.Column('status', sa.String(50), default='active'),
        sa.Column('cancellation_date', sa.Date()),
        sa.Column('cancellation_reason', sa.Text()),
        sa.Column('lien_marked', sa.Boolean(), default=False),
        sa.Column('lien_holder_name', sa.String(200)),
        sa.Column('lien_marked_date', sa.Date()),
        sa.Column('lien_removed_date', sa.Date()),
        sa.Column('claims_count', sa.Integer(), default=0),
        sa.Column('last_claim_date', sa.Date()),
        sa.Column('total_claim_amount', sa.Numeric(15, 2), default=0),
        sa.Column('nominee_name', sa.String(200)),
        sa.Column('nominee_relationship', sa.String(50)),
        sa.Column('policy_document_path', sa.String(500)),
        sa.Column('premium_receipt_path', sa.String(500)),
        sa.Column('expiry_alert_sent', sa.Boolean(), default=False),
        sa.Column('expiry_alert_date', sa.Date()),
        sa.Column('days_to_expiry', sa.Integer()),
        sa.Column('additional_info', postgresql.JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('created_by', postgresql.UUID(as_uuid=True)),
        sa.Column('updated_by', postgresql.UUID(as_uuid=True)),
        sa.Column('is_deleted', sa.Boolean(), default=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['vehicle_loan_id'], ['vehicle_loan_details.id']),
        sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id']),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id']),
        sa.UniqueConstraint('policy_number')
    )
    op.create_index('idx_insurance_tenant_vehicle', 'vehicle_insurance', ['tenant_id', 'vehicle_loan_id'])
    op.create_index('idx_insurance_expiry', 'vehicle_insurance', ['tenant_id', 'policy_end_date', 'status'])
    op.create_index('idx_insurance_customer', 'vehicle_insurance', ['tenant_id', 'customer_id'])
    
    # Vehicle Insurance Claims Table
    op.create_table(
        'vehicle_insurance_claims',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(50), nullable=False),
        sa.Column('insurance_id', sa.Integer(), nullable=False),
        sa.Column('claim_number', sa.String(50), nullable=False),
        sa.Column('claim_date', sa.Date(), nullable=False),
        sa.Column('incident_date', sa.Date(), nullable=False),
        sa.Column('incident_location', sa.String(200)),
        sa.Column('claim_type', sa.String(50), nullable=False),
        sa.Column('claim_description', sa.Text()),
        sa.Column('police_fir_number', sa.String(50)),
        sa.Column('police_station', sa.String(200)),
        sa.Column('claimed_amount', sa.Numeric(15, 2), nullable=False),
        sa.Column('approved_amount', sa.Numeric(15, 2)),
        sa.Column('settled_amount', sa.Numeric(15, 2)),
        sa.Column('deductible_amount', sa.Numeric(15, 2)),
        sa.Column('claim_status', sa.String(50), default='submitted'),
        sa.Column('surveyor_name', sa.String(200)),
        sa.Column('surveyor_contact', sa.String(20)),
        sa.Column('survey_date', sa.Date()),
        sa.Column('survey_report_number', sa.String(50)),
        sa.Column('survey_report_path', sa.String(500)),
        sa.Column('settlement_date', sa.Date()),
        sa.Column('settlement_mode', sa.String(50)),
        sa.Column('settlement_reference', sa.String(100)),
        sa.Column('rejection_date', sa.Date()),
        sa.Column('rejection_reason', sa.Text()),
        sa.Column('claim_form_path', sa.String(500)),
        sa.Column('repair_estimate_path', sa.String(500)),
        sa.Column('repair_invoice_path', sa.String(500)),
        sa.Column('photos_path', postgresql.JSONB()),
        sa.Column('additional_info', postgresql.JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('created_by', postgresql.UUID(as_uuid=True)),
        sa.Column('updated_by', postgresql.UUID(as_uuid=True)),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['insurance_id'], ['vehicle_insurance.id']),
        sa.UniqueConstraint('claim_number')
    )
    op.create_index('idx_claim_tenant_insurance', 'vehicle_insurance_claims', ['tenant_id', 'insurance_id'])
    op.create_index('idx_claim_status', 'vehicle_insurance_claims', ['tenant_id', 'claim_status'])
    
    # Vehicle Manufacturer Models Table (Master Data)
    op.create_table(
        'vehicle_manufacturer_models',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(50), nullable=False),
        sa.Column('manufacturer', sa.String(100), nullable=False),
        sa.Column('manufacturer_code', sa.String(50)),
        sa.Column('model', sa.String(100), nullable=False),
        sa.Column('model_code', sa.String(50)),
        sa.Column('variant', sa.String(100)),
        sa.Column('vehicle_type', sa.String(50), nullable=False),
        sa.Column('body_type', sa.String(50)),
        sa.Column('fuel_type', sa.String(50)),
        sa.Column('engine_capacity', sa.Integer()),
        sa.Column('seating_capacity', sa.Integer()),
        sa.Column('mileage', sa.Numeric(5, 2)),
        sa.Column('power_bhp', sa.Integer()),
        sa.Column('ex_showroom_price_min', sa.Numeric(15, 2)),
        sa.Column('ex_showroom_price_max', sa.Numeric(15, 2)),
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.Column('is_popular', sa.Boolean(), default=False),
        sa.Column('additional_info', postgresql.JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('is_deleted', sa.Boolean(), default=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'])
    )
    op.create_index('idx_vehicle_model_tenant', 'vehicle_manufacturer_models', ['tenant_id', 'manufacturer', 'model'])
    op.create_index('idx_vehicle_model_type', 'vehicle_manufacturer_models', ['tenant_id', 'vehicle_type', 'is_active'])
    
    # ============================================
    # PROPERTY LOAN TABLES
    # ============================================
    
    # Property Loan Details Table
    op.create_table(
        'property_loan_details',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(50), nullable=False),
        sa.Column('loan_application_id', sa.Integer(), nullable=False),
        sa.Column('property_type', sa.String(50), nullable=False),
        sa.Column('property_ownership_type', sa.String(50), nullable=False),
        sa.Column('property_status', sa.String(50), nullable=False),
        sa.Column('address_line1', sa.String(200), nullable=False),
        sa.Column('address_line2', sa.String(200)),
        sa.Column('city', sa.String(100), nullable=False),
        sa.Column('district', sa.String(100)),
        sa.Column('state', sa.String(50), nullable=False),
        sa.Column('pincode', sa.String(10), nullable=False),
        sa.Column('landmark', sa.String(200)),
        sa.Column('survey_number', sa.String(100)),
        sa.Column('plot_number', sa.String(50)),
        sa.Column('khata_number', sa.String(50)),
        sa.Column('khasra_number', sa.String(50)),
        sa.Column('cts_number', sa.String(50)),
        sa.Column('block_number', sa.String(50)),
        sa.Column('flat_number', sa.String(50)),
        sa.Column('building_name', sa.String(200)),
        sa.Column('plot_area', sa.Numeric(10, 2)),
        sa.Column('built_up_area', sa.Numeric(10, 2)),
        sa.Column('carpet_area', sa.Numeric(10, 2)),
        sa.Column('construction_year', sa.Integer()),
        sa.Column('property_age', sa.Integer()),
        sa.Column('number_of_floors', sa.Integer()),
        sa.Column('floor_number', sa.Integer()),
        sa.Column('number_of_rooms', sa.Integer()),
        sa.Column('number_of_bathrooms', sa.Integer()),
        sa.Column('boundary_north', sa.String(200)),
        sa.Column('boundary_south', sa.String(200)),
        sa.Column('boundary_east', sa.String(200)),
        sa.Column('boundary_west', sa.String(200)),
        sa.Column('market_value', sa.Numeric(15, 2), nullable=False),
        sa.Column('distress_sale_value', sa.Numeric(15, 2)),
        sa.Column('government_value', sa.Numeric(15, 2)),
        sa.Column('bank_valuation', sa.Numeric(15, 2)),
        sa.Column('loan_amount', sa.Numeric(15, 2), nullable=False),
        sa.Column('loan_to_value', sa.Numeric(5, 2)),
        sa.Column('current_owner_name', sa.String(200)),
        sa.Column('previous_owner_name', sa.String(200)),
        sa.Column('ownership_duration', sa.Integer()),
        sa.Column('builder_name', sa.String(200)),
        sa.Column('builder_contact', sa.String(20)),
        sa.Column('builder_registration', sa.String(100)),
        sa.Column('seller_name', sa.String(200)),
        sa.Column('seller_contact', sa.String(20)),
        sa.Column('is_disputed', sa.Boolean(), default=False),
        sa.Column('has_clear_title', sa.Boolean(), default=False),
        sa.Column('has_litigation', sa.Boolean(), default=False),
        sa.Column('litigation_details', sa.Text()),
        sa.Column('has_building_approval', sa.Boolean(), default=False),
        sa.Column('has_occupation_certificate', sa.Boolean(), default=False),
        sa.Column('has_completion_certificate', sa.Boolean(), default=False),
        sa.Column('has_electricity', sa.Boolean(), default=False),
        sa.Column('has_water_connection', sa.Boolean(), default=False),
        sa.Column('has_drainage', sa.Boolean(), default=False),
        sa.Column('legal_verification_status', sa.String(50), default='pending'),
        sa.Column('technical_verification_status', sa.String(50), default='pending'),
        sa.Column('mortgage_status', sa.String(50), default='pending'),
        sa.Column('additional_info', postgresql.JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('created_by', postgresql.UUID(as_uuid=True)),
        sa.Column('updated_by', postgresql.UUID(as_uuid=True)),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id']),
        sa.UniqueConstraint('loan_application_id')
    )
    op.create_index('idx_property_tenant_loan', 'property_loan_details', ['tenant_id', 'loan_application_id'])
    op.create_index('idx_property_type_status', 'property_loan_details', ['tenant_id', 'property_type', 'property_status'])
    op.create_index('idx_property_location', 'property_loan_details', ['city', 'state', 'pincode'])
    
    # Property Legal Verification Table
    op.create_table(
        'property_legal_verification',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(50), nullable=False),
        sa.Column('property_loan_id', sa.Integer(), nullable=False),
        sa.Column('loan_application_id', sa.Integer(), nullable=False),
        sa.Column('advocate_name', sa.String(200)),
        sa.Column('advocate_contact', sa.String(20)),
        sa.Column('advocate_bar_registration', sa.String(100)),
        sa.Column('legal_firm_name', sa.String(200)),
        sa.Column('verification_date', sa.Date()),
        sa.Column('verification_reference', sa.String(100)),
        sa.Column('verification_fees', sa.Numeric(10, 2)),
        sa.Column('title_clear', sa.Boolean(), default=False),
        sa.Column('title_issues', sa.Text()),
        sa.Column('title_chain_verified', sa.Boolean(), default=False),
        sa.Column('previous_owners', postgresql.JSONB()),
        sa.Column('ec_obtained', sa.Boolean(), default=False),
        sa.Column('ec_period_from', sa.Date()),
        sa.Column('ec_period_to', sa.Date()),
        sa.Column('ec_reference_number', sa.String(100)),
        sa.Column('ec_issues_found', sa.Text()),
        sa.Column('encumbrances_found', sa.Boolean(), default=False),
        sa.Column('encumbrance_details', sa.Text()),
        sa.Column('search_report_available', sa.Boolean(), default=False),
        sa.Column('search_report_date', sa.Date()),
        sa.Column('search_years_covered', sa.Integer()),
        sa.Column('property_tax_verified', sa.Boolean(), default=False),
        sa.Column('property_tax_updated', sa.Boolean(), default=False),
        sa.Column('property_tax_arrears', sa.Numeric(10, 2)),
        sa.Column('sale_deed_verified', sa.Boolean(), default=False),
        sa.Column('sale_deed_date', sa.Date()),
        sa.Column('sale_deed_value', sa.Numeric(15, 2)),
        sa.Column('gift_deed_applicable', sa.Boolean(), default=False),
        sa.Column('inheritance_verified', sa.Boolean(), default=False),
        sa.Column('poa_verified', sa.Boolean(), default=False),
        sa.Column('poa_holder_name', sa.String(200)),
        sa.Column('poa_registration_date', sa.Date()),
        sa.Column('poa_valid', sa.Boolean(), default=False),
        sa.Column('mother_deed_verified', sa.Boolean(), default=False),
        sa.Column('mother_deed_date', sa.Date()),
        sa.Column('legal_opinion_given', sa.Boolean(), default=False),
        sa.Column('legal_opinion_date', sa.Date()),
        sa.Column('legal_opinion_summary', sa.Text()),
        sa.Column('legal_opinion_status', sa.String(50), default='pending'),
        sa.Column('litigation_pending', sa.Boolean(), default=False),
        sa.Column('litigation_details', sa.Text()),
        sa.Column('legal_risks_identified', sa.Text()),
        sa.Column('recommendations', sa.Text()),
        sa.Column('approved', sa.Boolean(), default=False),
        sa.Column('approved_date', sa.Date()),
        sa.Column('rejection_reason', sa.Text()),
        sa.Column('legal_report_path', sa.String(500)),
        sa.Column('ec_document_path', sa.String(500)),
        sa.Column('search_report_path', sa.String(500)),
        sa.Column('additional_info', postgresql.JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('created_by', postgresql.UUID(as_uuid=True)),
        sa.Column('updated_by', postgresql.UUID(as_uuid=True)),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['property_loan_id'], ['property_loan_details.id']),
        sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id']),
        sa.UniqueConstraint('property_loan_id')
    )
    op.create_index('idx_legal_tenant_property', 'property_legal_verification', ['tenant_id', 'property_loan_id'])
    op.create_index('idx_legal_status', 'property_legal_verification', ['tenant_id', 'legal_opinion_status'])
    
    # Property Technical Verification Table
    op.create_table(
        'property_technical_verification',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(50), nullable=False),
        sa.Column('property_loan_id', sa.Integer(), nullable=False),
        sa.Column('loan_application_id', sa.Integer(), nullable=False),
        sa.Column('engineer_name', sa.String(200)),
        sa.Column('engineer_contact', sa.String(20)),
        sa.Column('engineer_license', sa.String(100)),
        sa.Column('valuer_empaneled', sa.Boolean(), default=False),
        sa.Column('inspection_date', sa.Date()),
        sa.Column('inspection_time', sa.String(20)),
        sa.Column('inspection_reference', sa.String(100)),
        sa.Column('inspection_fees', sa.Numeric(10, 2)),
        sa.Column('site_visited', sa.Boolean(), default=False),
        sa.Column('site_accessible', sa.Boolean(), default=True),
        sa.Column('site_location_verified', sa.Boolean(), default=False),
        sa.Column('boundaries_verified', sa.Boolean(), default=False),
        sa.Column('plot_area_verified', sa.Numeric(10, 2)),
        sa.Column('built_up_area_verified', sa.Numeric(10, 2)),
        sa.Column('carpet_area_verified', sa.Numeric(10, 2)),
        sa.Column('measurement_variance', sa.Numeric(5, 2)),
        sa.Column('construction_type', sa.String(50)),
        sa.Column('construction_quality', sa.String(50)),
        sa.Column('construction_stage', sa.String(50)),
        sa.Column('construction_completion', sa.Integer()),
        sa.Column('property_condition', sa.String(50)),
        sa.Column('property_age_verified', sa.Integer()),
        sa.Column('property_maintenance', sa.String(50)),
        sa.Column('structural_issues', sa.Text()),
        sa.Column('repair_required', sa.Boolean(), default=False),
        sa.Column('repair_cost_estimate', sa.Numeric(10, 2)),
        sa.Column('floor_type', sa.String(50)),
        sa.Column('roof_type', sa.String(50)),
        sa.Column('window_type', sa.String(50)),
        sa.Column('door_type', sa.String(50)),
        sa.Column('electricity_verified', sa.Boolean(), default=False),
        sa.Column('water_supply_verified', sa.Boolean(), default=False),
        sa.Column('drainage_verified', sa.Boolean(), default=False),
        sa.Column('road_access', sa.Boolean(), default=True),
        sa.Column('road_width', sa.Numeric(5, 2)),
        sa.Column('building_plan_approved', sa.Boolean(), default=False),
        sa.Column('building_plan_number', sa.String(100)),
        sa.Column('building_plan_authority', sa.String(200)),
        sa.Column('occupation_certificate_verified', sa.Boolean(), default=False),
        sa.Column('oc_number', sa.String(100)),
        sa.Column('oc_date', sa.Date()),
        sa.Column('completion_certificate_verified', sa.Boolean(), default=False),
        sa.Column('cc_number', sa.String(100)),
        sa.Column('cc_date', sa.Date()),
        sa.Column('locality_type', sa.String(50)),
        sa.Column('neighborhood_development', sa.String(50)),
        sa.Column('distance_to_main_road', sa.Numeric(5, 2)),
        sa.Column('public_transport_available', sa.Boolean(), default=True),
        sa.Column('market_value_assessed', sa.Numeric(15, 2)),
        sa.Column('distress_sale_value_assessed', sa.Numeric(15, 2)),
        sa.Column('forced_sale_value', sa.Numeric(15, 2)),
        sa.Column('realizable_value', sa.Numeric(15, 2)),
        sa.Column('valuation_method', sa.String(50)),
        sa.Column('recommended_loan_amount', sa.Numeric(15, 2)),
        sa.Column('recommended_ltv', sa.Numeric(5, 2)),
        sa.Column('property_marketable', sa.Boolean(), default=True),
        sa.Column('remarks', sa.Text()),
        sa.Column('risks_identified', sa.Text()),
        sa.Column('status', sa.String(50), default='pending'),
        sa.Column('approved', sa.Boolean(), default=False),
        sa.Column('approved_date', sa.Date()),
        sa.Column('rejection_reason', sa.Text()),
        sa.Column('valuation_report_path', sa.String(500)),
        sa.Column('site_photos', postgresql.JSONB()),
        sa.Column('video_path', sa.String(500)),
        sa.Column('additional_info', postgresql.JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('created_by', postgresql.UUID(as_uuid=True)),
        sa.Column('updated_by', postgresql.UUID(as_uuid=True)),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['property_loan_id'], ['property_loan_details.id']),
        sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id']),
        sa.UniqueConstraint('property_loan_id')
    )
    op.create_index('idx_technical_tenant_property', 'property_technical_verification', ['tenant_id', 'property_loan_id'])
    op.create_index('idx_technical_status', 'property_technical_verification', ['tenant_id', 'status'])
    
    # Property Documents Table
    op.create_table(
        'property_documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(50), nullable=False),
        sa.Column('property_loan_id', sa.Integer(), nullable=False),
        sa.Column('loan_application_id', sa.Integer(), nullable=False),
        sa.Column('document_type', sa.String(100), nullable=False),
        sa.Column('document_name', sa.String(200), nullable=False),
        sa.Column('document_number', sa.String(100)),
        sa.Column('document_date', sa.Date()),
        sa.Column('file_path', sa.String(500), nullable=False),
        sa.Column('file_name', sa.String(200)),
        sa.Column('file_size', sa.Integer()),
        sa.Column('mime_type', sa.String(100)),
        sa.Column('is_verified', sa.Boolean(), default=False),
        sa.Column('verified_by', postgresql.UUID(as_uuid=True)),
        sa.Column('verified_date', sa.Date()),
        sa.Column('verification_remarks', sa.Text()),
        sa.Column('is_original', sa.Boolean(), default=False),
        sa.Column('is_certified_copy', sa.Boolean(), default=False),
        sa.Column('issuing_authority', sa.String(200)),
        sa.Column('additional_info', postgresql.JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('uploaded_by', postgresql.UUID(as_uuid=True)),
        sa.Column('is_deleted', sa.Boolean(), default=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['property_loan_id'], ['property_loan_details.id']),
        sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'])
    )
    op.create_index('idx_document_tenant_property', 'property_documents', ['tenant_id', 'property_loan_id'])
    op.create_index('idx_document_type', 'property_documents', ['tenant_id', 'document_type'])
    
    # Property Mortgage Table
    op.create_table(
        'property_mortgages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(50), nullable=False),
        sa.Column('property_loan_id', sa.Integer(), nullable=False),
        sa.Column('loan_application_id', sa.Integer(), nullable=False),
        sa.Column('mortgage_type', sa.String(50), nullable=False),
        sa.Column('mortgage_deed_number', sa.String(100)),
        sa.Column('mortgage_amount', sa.Numeric(15, 2), nullable=False),
        sa.Column('sub_registrar_office', sa.String(200)),
        sa.Column('sub_registrar_district', sa.String(100)),
        sa.Column('registration_date', sa.Date()),
        sa.Column('registration_number', sa.String(100)),
        sa.Column('registration_fees', sa.Numeric(10, 2)),
        sa.Column('stamp_duty_paid', sa.Numeric(10, 2)),
        sa.Column('lien_marked', sa.Boolean(), default=False),
        sa.Column('lien_marked_date', sa.Date()),
        sa.Column('lien_holder_name', sa.String(200)),
        sa.Column('lien_amount', sa.Numeric(15, 2)),
        sa.Column('mortgage_status', sa.String(50), default='pending'),
        sa.Column('original_documents_submitted', sa.Boolean(), default=False),
        sa.Column('documents_submission_date', sa.Date()),
        sa.Column('documents_received_from', sa.String(200)),
        sa.Column('sale_deed_original', sa.Boolean(), default=False),
        sa.Column('property_card_original', sa.Boolean(), default=False),
        sa.Column('building_plan_original', sa.Boolean(), default=False),
        sa.Column('other_documents', postgresql.JSONB()),
        sa.Column('loan_closed_date', sa.Date()),
        sa.Column('discharge_initiated', sa.Boolean(), default=False),
        sa.Column('discharge_initiated_date', sa.Date()),
        sa.Column('discharge_deed_executed', sa.Boolean(), default=False),
        sa.Column('discharge_deed_date', sa.Date()),
        sa.Column('discharge_deed_number', sa.String(100)),
        sa.Column('discharge_registered', sa.Boolean(), default=False),
        sa.Column('discharge_registration_date', sa.Date()),
        sa.Column('discharge_registration_number', sa.String(100)),
        sa.Column('documents_returned', sa.Boolean(), default=False),
        sa.Column('documents_return_date', sa.Date()),
        sa.Column('documents_returned_to', sa.String(200)),
        sa.Column('last_followup_date', sa.Date()),
        sa.Column('next_followup_date', sa.Date()),
        sa.Column('followup_remarks', sa.Text()),
        sa.Column('mortgage_deed_path', sa.String(500)),
        sa.Column('discharge_deed_path', sa.String(500)),
        sa.Column('acknowledgement_path', sa.String(500)),
        sa.Column('additional_info', postgresql.JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('created_by', postgresql.UUID(as_uuid=True)),
        sa.Column('updated_by', postgresql.UUID(as_uuid=True)),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['property_loan_id'], ['property_loan_details.id']),
        sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id']),
        sa.UniqueConstraint('property_loan_id')
    )
    op.create_index('idx_mortgage_tenant_property', 'property_mortgages', ['tenant_id', 'property_loan_id'])
    op.create_index('idx_mortgage_status', 'property_mortgages', ['tenant_id', 'mortgage_status'])


def downgrade():
    """Drop vehicle and property loan extension tables"""
    
    # Drop Property Loan Tables
    op.drop_table('property_mortgages')
    op.drop_table('property_documents')
    op.drop_table('property_technical_verification')
    op.drop_table('property_legal_verification')
    op.drop_table('property_loan_details')
    
    # Drop Vehicle Loan Tables
    op.drop_table('vehicle_manufacturer_models')
    op.drop_table('vehicle_insurance_claims')
    op.drop_table('vehicle_insurance')
    op.drop_table('vehicle_rto_tracking')
    op.drop_table('vehicle_loan_details')
    op.drop_table('vehicle_dealers')
