import type { DashboardWidgetContract } from './types';

export const dashboardWidgetRegistry: DashboardWidgetContract[] = [
  {
    id: 'kpi-widget',
    title: 'KPI Widget',
    category: 'kpi',
    refreshPolicy: '30-60 seconds',
    drilldownTarget: '/dashboard/kpi/:id',
    exportable: true,
    supportedSizes: ['sm', 'md'],
  },
  {
    id: 'chart-widget',
    title: 'Chart Widget',
    category: 'chart',
    refreshPolicy: '1-5 minutes',
    drilldownTarget: '/dashboard/charts/:id',
    exportable: true,
    supportedSizes: ['lg', 'xl', 'full'],
  },
  {
    id: 'alert-widget',
    title: 'Alert Widget',
    category: 'alert',
    permissions: ['alerts.read'],
    refreshPolicy: '30 seconds',
    drilldownTarget: '/alerts',
    exportable: false,
    supportedSizes: ['md', 'lg'],
  },
  {
    id: 'task-widget',
    title: 'Task Widget',
    category: 'task',
    permissions: ['tasks.read'],
    refreshPolicy: '30 seconds',
    drilldownTarget: '/tasks',
    exportable: false,
    supportedSizes: ['md', 'lg'],
  },
  {
    id: 'approval-widget',
    title: 'Approval Widget',
    category: 'approval',
    permissions: ['approvals.read'],
    refreshPolicy: '30 seconds',
    drilldownTarget: '/approvals',
    exportable: false,
    supportedSizes: ['lg', 'full'],
  },
  {
    id: 'activity-widget',
    title: 'Activity Widget',
    category: 'activity',
    refreshPolicy: '1 minute',
    drilldownTarget: '/activity',
    exportable: true,
    supportedSizes: ['md', 'lg'],
  },
  {
    id: 'ai-summary-widget',
    title: 'AI Summary Widget',
    category: 'ai',
    permissions: ['ai.read'],
    refreshPolicy: 'on demand',
    drilldownTarget: '/ai/insights',
    exportable: false,
    supportedSizes: ['lg', 'xl'],
  },
];
